name: publish
on:
  push:
    branches:
      - release

defaults:
  run:
    shell: bash
    working-directory: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: install yarn
        run: corepack enable && corepack prepare yarn@stable --activate
      - name: run build
        run: |
          yarn
          yarn test --run
          yarn build
      - name: publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.PERSONAL_NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_NPM_TOKEN }}
